# base image
FROM python:3.9-slim AS python_base

# set work directory
WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install python dependencies
RUN python -m pip install --upgrade pip
COPY requirements.txt /usr/src/app/
RUN pip install -r requirements.txt

# run entrypoint.sh
ENTRYPOINT ["sh", "devops/docker/web/entrypoint.sh"]

# copy to workdir
COPY . /usr/src/app/