version: "3.9"

services:
    db:
        image: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_DB=test_db
            - POSTGRES_USER=ahtle
            - POSTGRES_PASSWORD=secret
        ports:
            - 5432:5432
    
    web:
        build:
            context: ./
            dockerfile: ./devops/docker/web/Dockerfile.dev
            target: python_base
        restart:  always
        volumes: 
            - .:/usr/src/app
        ports:
            - 8000:8000
        env_file: 
            - ./.env.dev
        depends_on: 
            - db

volumes:
    postgres_data: