version: "3.9"

services:
    db:
        image: postgres
        volumes: 
            - postgres_data:/var/lib/postgresql/data/
        environment: :
            - POSTGRES_DB=test_db
            - POSTGRES_USER=ahtle
            - POSTGRES_PASSWORD=secret
        ports:
            - 5432:5432
    
    #   ---------- EXAMPLE with alphine ----------
    #   db:
    #     image: postgres:12.0-alpine
    #     volumes:
    #       - postgres_data:/var/lib/postgresql/data/
    #     environment:
    #       - POSTGRES_USER=spark
    #       - POSTGRES_PASSWORD=spark
    #       - POSTGRES_DB=spk_agent_tools
    #     ports:
    #       - 5432:5432
    
    
    web:
        build:
            context: ./devops/docker/web/
            dockerfile: Dockerfile.dev
            target: python_base
        restart:  always
        command: python manage.py runserver 0.0.0.0:8000
        volumes: 
            - .:/usr/src/app
        ports:
            - 8000:8000
        env_file: 
            - ./.env.dev
        depends_on: 
            - db
        

    #   ---------- EXAMPLE ----------

    # web:
    #     build:
    #       context: ./
    #       dockerfile: ./devops/docker/web/Dockerfile.dev
    #       target: python_base
    #     restart: always
    #     command: gunicorn provider_search.wsgi:application  --reload --bind 0.0.0.0:8000 --access-logfile '-'
    #     volumes:
    #       - ./static:/usr/src/app/staticfiles
    #       - ./media:/usr/src/app/media
    #       - .:/usr/src/app
    #     ports:
    #       - 8000:8000
    #     env_file:
    #       - ./.env.dev
    #     depends_on:
    #       - db
